import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { type FormEvent, useEffect, useState } from "react";

import { ApiError } from "../../app/api/client";
import { lifeApi, type GoalDirection, type GoalRecommendation } from "../../app/api/life";
import { IconButton, LifeSelect, SectionHeading, StatusChip, Toggle, PageHeader } from "./LifeUI";
import { Icon } from "./icons";

export function SettingsPage() {
  const client = useQueryClient();
  const profile = useQuery({ queryKey: ["life", "profile"], queryFn: lifeApi.profile });
  const goals = useQuery({ queryKey: ["life", "goals"], queryFn: lifeApi.goals });
  const candidates = useQuery({ queryKey: ["life", "destination-candidates"], queryFn: lifeApi.candidates });
  const destinations = useQuery({ queryKey: ["life", "destinations"], queryFn: lifeApi.destinations });
  const [preferenceOpen, setPreferenceOpen] = useState(false);
  const goalPreference = useQuery({ queryKey: ["life", "goal-preferences"], queryFn: lifeApi.goalPreferences, enabled: preferenceOpen });
  const goalRecommendations = useQuery({ queryKey: ["life", "goal-recommendations"], queryFn: lifeApi.goalRecommendations, enabled: preferenceOpen });
  const [goalDirection, setGoalDirection] = useState<GoalDirection | "">("");
  const [message, setMessage] = useState<string | null>(null);
  useEffect(() => { setGoalDirection(goalPreference.data?.goal_direction ?? ""); }, [goalPreference.data]);
  const refresh = () => Promise.all([client.invalidateQueries({ queryKey: ["life", "profile"] }), client.invalidateQueries({ queryKey: ["life", "goals"] }), client.invalidateQueries({ queryKey: ["life", "destination-candidates"] }), client.invalidateQueries({ queryKey: ["life", "destinations"] })]);
  const saveProfile = useMutation({ mutationFn: lifeApi.saveProfile, onSuccess: () => { setMessage("Profile saved."); return refresh(); }, onError: (error) => setMessage(publicError(error)) });
  const createGoal = useMutation({ mutationFn: lifeApi.createGoal, onSuccess: () => { setMessage("Nutrition target saved."); return refresh(); }, onError: (error) => setMessage(publicError(error)) });
  const activate = useMutation({ mutationFn: ({ id, makeDefault }: { id: number; makeDefault: boolean }) => lifeApi.activateCandidate(id, { make_default: makeDefault }), onSuccess: () => { setMessage("Destination activated."); return refresh(); }, onError: (error) => setMessage(publicError(error)) });
  const patchDestination = useMutation({ mutationFn: ({ id, value }: { id: number; value: object }) => lifeApi.patchDestination(id, value), onSuccess: refresh });
  const saveGoalPreference = useMutation({ mutationFn: lifeApi.saveGoalPreference, onSuccess: async () => { setMessage("Weight trend preference saved."); await Promise.all([client.invalidateQueries({ queryKey: ["life", "goal-preferences"] }), client.invalidateQueries({ queryKey: ["life", "goal-recommendations"] })]); }, onError: (error) => setMessage(publicError(error)) });

  if ([profile, goals, candidates, destinations].some((query) => query.isPending)) return <SettingsState text="Loading settings…" />;
  if ([profile, goals, candidates, destinations].some((query) => query.isError)) return <SettingsState text={publicError(profile.error ?? goals.error ?? candidates.error ?? destinations.error)} error />;

  const currentGoal = goals.data[0];
  const profileName = profile.data?.display_name || "Your Life profile";
  return <section className="life-page"><PageHeader eyebrow="Make Life fit you" title="Settings" description="A few thoughtful defaults keep the everyday view simple." />{message && <p className="form-message" role="status">{message}</p>}<section className="profile-banner"><span className="profile-avatar"><Icon name="user" size={22} /></span><div><h2>{profileName}</h2><p>Life profile <span aria-hidden="true">·</span> {profile.data?.timezone ?? "Timezone not set"}</p></div></section>
    <section className="settings-section"><SectionHeading eyebrow="Who you are" title="Profile" /><details className="settings-group settings-disclosure"><summary className="settings-row"><span className="settings-icon"><Icon name="user" size={17} /></span><span className="settings-row-main"><strong>Profile details</strong><small>{profile.data?.display_name || "Add your display name and timezone"}</small></span><span className="settings-value">{profile.data?.timezone ?? "Not set"}</span><Icon name="chevron" className="row-chevron" size={16} /></summary><form className="settings-form" onSubmit={(event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); saveProfile.mutate({ timezone: String(form.get("timezone")), display_name: String(form.get("display_name") || "") || null, height_cm: String(form.get("height_cm") || "") || null, sex: String(form.get("sex") || "") || null } as never); }}><div className="field-grid"><label className="field"><span>Timezone</span><input name="timezone" defaultValue={profile.data?.timezone ?? Intl.DateTimeFormat().resolvedOptions().timeZone} required /></label><label className="field"><span>Display name</span><input name="display_name" defaultValue={profile.data?.display_name ?? ""} /></label><label className="field"><span>Height (cm)</span><input name="height_cm" type="number" step="0.01" defaultValue={profile.data?.height_cm ?? ""} /></label><label className="field"><span>Sex</span><select name="sex" defaultValue={profile.data?.sex ?? ""}><option value="">Prefer not to set</option><option value="female">Female</option><option value="male">Male</option><option value="other">Other</option><option value="prefer_not_to_say">Prefer not to say</option></select></label></div><button className="button button-primary" disabled={saveProfile.isPending}>{saveProfile.isPending ? "Saving…" : "Save profile"}</button></form></details></section>
    <section className="settings-section"><SectionHeading eyebrow="Your daily baseline" title="Nutrition targets" action={<span className="section-count">{currentGoal ? "Configured" : "Not set"}</span>} /><details className="settings-group settings-disclosure"><summary className="settings-row"><span className="settings-icon settings-icon-green"><Icon name="flame" size={17} /></span><span className="settings-row-main"><strong>Calorie target</strong><small>{currentGoal ? `Effective from ${currentGoal.effective_from}` : "Set a daily energy goal"}</small></span><span className="settings-value">{currentGoal ? `${currentGoal.calorie_target_kcal} kcal` : "Not set"}</span><Icon name="chevron" className="row-chevron" size={16} /></summary><form className="settings-form" onSubmit={(event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); createGoal.mutate({ calorie_target_kcal: Number(form.get("calories")), protein_min_g: String(form.get("protein_min")), protein_max_g: String(form.get("protein_max")), effective_from: String(form.get("effective_from")) }); }}><div className="field-grid"><label className="field"><span>Calories</span><input name="calories" type="number" min="1" defaultValue={currentGoal?.calorie_target_kcal ?? ""} required /></label><label className="field"><span>Effective from</span><input name="effective_from" type="date" defaultValue={currentGoal?.effective_from ?? new Date().toISOString().slice(0, 10)} required /></label><label className="field"><span>Protein minimum (g)</span><input name="protein_min" type="number" min="0" step="0.01" defaultValue={currentGoal?.protein_min_g ?? ""} required /></label><label className="field"><span>Protein maximum (g)</span><input name="protein_max" type="number" min="0" step="0.01" defaultValue={currentGoal?.protein_max_g ?? ""} required /></label></div><button className="button button-primary" disabled={createGoal.isPending}>{createGoal.isPending ? "Saving…" : "Save target"}</button></form></details></section>
    <section className="settings-section"><SectionHeading eyebrow="A gentle guide, never automatic" title="Weight trend preferences" /><details className="settings-group settings-disclosure" onToggle={(event) => setPreferenceOpen(event.currentTarget.open)}><summary className="settings-row"><span className="settings-icon settings-icon-green"><Icon name="trend" size={17} /></span><span className="settings-row-main"><strong>Weight trend preferences</strong><small>{goalPreference.data ? goalDirectionLabel(goalPreference.data.goal_direction) : "Tell Life whether you want to lose, maintain, or gain weight"}</small></span><span className="settings-value">{goalPreference.data ? goalDirectionLabel(goalPreference.data.goal_direction) : "Not set"}</span><Icon name="chevron" className="row-chevron" size={16} /></summary>{preferenceOpen && (goalPreference.isPending ? <p className="settings-inline-state muted">Loading preference…</p> : goalPreference.isError ? <p className="settings-inline-state form-error" role="alert">{publicError(goalPreference.error)}</p> : <form className="settings-form weight-preference-form" onSubmit={(event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); const desired = String(form.get("desired_weekly_change_kg") || "").trim(); if (!goalDirection) return; saveGoalPreference.mutate({ goal_direction: goalDirection, desired_weekly_change_kg: desired ? Number(desired) : null }); }}><div className="field-grid"><label className="field"><span>Direction</span><LifeSelect name="goal_direction" value={goalDirection} onChange={(value) => setGoalDirection(value as GoalDirection)} options={[{ value: "lose_weight", label: "Lose weight" }, { value: "maintain_weight", label: "Maintain weight" }, { value: "gain_weight", label: "Gain weight" }]} placeholder="Select a direction" required /></label><label className="field"><span>Desired weekly change (kg)</span><input name="desired_weekly_change_kg" type="number" step="0.01" min={goalDirection === "lose_weight" ? -5 : 0} max={goalDirection === "gain_weight" ? 5 : 0} defaultValue={goalPreference.data?.desired_weekly_change_kg ?? ""} placeholder="-0.25, 0, or 0.25" /></label></div><p className="settings-form-note">Life uses this preference to explain possible calorie changes. It will never change your target automatically.</p>{goalPreference.data?.last_evaluated_on && <p className="settings-form-note">Last evaluated: {formatDateOnly(goalPreference.data.last_evaluated_on)}</p>}<button className="button button-primary" disabled={saveGoalPreference.isPending || !goalDirection}>{saveGoalPreference.isPending ? "Saving…" : "Save preference"}</button></form>)}{preferenceOpen && <GoalRecommendationHistory recommendations={goalRecommendations.data ?? []} pending={goalRecommendations.isPending} error={goalRecommendations.error} />}</details></section>
    <section className="settings-section"><SectionHeading eyebrow="Stay gently in sync" title="Notifications" /><div className="settings-group"><div className="settings-row"><span className="settings-icon"><Icon name="bell" size={17} /></span><span className="settings-row-main"><strong>Life reminders</strong><small>Destinations activated below receive your plans</small></span><span className="settings-value">{destinations.data.some((item) => item.enabled) ? "Enabled" : "Off"}</span></div>{destinations.data.map((item) => <div className="settings-row" key={item.id}><span className="settings-icon"><Icon name={item.kind === "private" ? "user" : "bell"} size={17} /></span><span className="settings-row-main"><strong>{item.label}</strong><small>{item.kind} {item.is_default ? "· Default" : "· Available"}</small></span><Toggle checked={item.enabled} label={`${item.enabled ? "Disable" : "Enable"} ${item.label}`} onChange={() => patchDestination.mutate({ id: item.id, value: { enabled: !item.enabled } })} />{item.enabled && !item.is_default && <IconButton label={`Make ${item.label} default`} icon="check" onClick={() => patchDestination.mutate({ id: item.id, value: { is_default: true } })} />}</div>)}{candidates.data.map((item) => <div className="settings-row" key={item.id}><span className="settings-icon"><Icon name="bell" size={17} /></span><span className="settings-row-main"><strong>{item.chat_label}</strong><small>{item.kind} via {item.bot_name} · not activated</small></span><button className="button button-secondary" type="button" onClick={() => activate.mutate({ id: item.id, makeDefault: destinations.data.length === 0 })}>Activate</button></div>)}</div><div className="warning-note"><span className="warning-icon"><Icon name="warning" size={17} /></span><p><strong>Group destinations stay off by default.</strong> Enable one only when you want Life reminders shared with that chat.</p></div></section>
    <section className="settings-section"><SectionHeading eyebrow="The quiet details" title="App & session" /><div className="settings-group"><div className="settings-row"><span className="settings-icon"><Icon name="leaf" size={17} /></span><span className="settings-row-main"><strong>Appearance</strong><small>Follow the Telegram theme</small></span><span className="settings-value">System</span></div><div className="settings-row"><span className="settings-icon"><Icon name="shield" size={17} /></span><span className="settings-row-main"><strong>Privacy</strong><small>Your personal Life data stays yours</small></span><span className="settings-value">Protected</span></div></div></section><p className="settings-footnote"><Icon name="logout" size={15} />Use the profile button in the top bar to log out.</p>
  </section>;
}

function publicError(error: unknown) { return error instanceof ApiError ? error.message : "The Settings request could not be completed."; }
function goalDirectionLabel(direction: GoalDirection) { return direction === "lose_weight" ? "Lose weight" : direction === "gain_weight" ? "Gain weight" : "Maintain weight"; }
function GoalRecommendationHistory({ recommendations, pending, error }: { recommendations: GoalRecommendation[]; pending: boolean; error: unknown }) {
  return <div className="recommendation-history"><div className="recommendation-history-heading"><div><strong>Recommendation history</strong><small>Read-only record of Life check-ins</small></div></div>{pending ? <p className="recommendation-history-state muted">Loading recommendation history…</p> : error ? <p className="recommendation-history-state form-error" role="alert">{publicError(error)}</p> : recommendations.length === 0 ? <p className="recommendation-history-state muted">No weight trend recommendations yet.</p> : recommendations.map((item) => <article className="recommendation-history-row" key={item.id}><div className="recommendation-history-main"><div className="row-title"><strong>{formatDate(item.offered_at)}</strong><StatusChip tone={recommendationStatusTone(item.status)}>{recommendationStatusLabel(item.status)}</StatusChip></div><p>{formatTrend(item.trend_kg_per_week)} <span aria-hidden="true">·</span> {item.observation_count} observations <span aria-hidden="true">·</span> {formatDateOnly(item.window_start)} – {formatDateOnly(item.window_end)}{item.delivery_status === "failed" && <span className="recommendation-delivery-failed"> · Delivery failed</span>}</p></div><div className="recommendation-history-value"><strong>{item.current_calorie_target_kcal.toLocaleString()} → {item.recommended_calorie_target_kcal.toLocaleString()}</strong><small>kcal/day</small></div></article>)}</div>;
}
function recommendationStatusLabel(status: GoalRecommendation["status"]) { return status === "applied" ? "Applied" : status === "dismissed" ? "Kept" : status === "expired" ? "Expired" : status === "superseded" ? "Superseded" : "Pending"; }
function recommendationStatusTone(status: GoalRecommendation["status"]): "green" | "warm" | "muted" | "danger" { return status === "applied" ? "green" : status === "pending" ? "warm" : status === "expired" ? "danger" : "muted"; }
function formatDate(value: string) { return new Date(value).toLocaleDateString([], { month: "short", day: "numeric", year: "numeric" }); }
function formatDateOnly(value: string) { return new Date(`${value}T00:00:00`).toLocaleDateString([], { month: "short", day: "numeric" }); }
function formatTrend(value: string) { const trend = Number(value); return Number.isFinite(trend) ? `${trend > 0 ? "+" : ""}${trend.toFixed(2)} kg/week` : `${value} kg/week`; }
function SettingsState({ text, error = false }: { text: string; error?: boolean }) { return <section className="life-page"><PageHeader eyebrow="Settings" title="Settings" /><p className={error ? "form-error" : "muted"} role={error ? "alert" : undefined}>{text}</p></section>; }
